name: speaker_diarization
channels:
  - conda-forge
  - pytorch
  - defaults
channel_priority: flexible
dependencies:
  - python=3.9
  - pip
  - numpy>=1.20.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - librosa>=0.8.1
  - matplotlib>=3.5.0
  - tqdm>=4.62.0
  - pandas>=1.3.0
  - pyyaml>=6.0
  - notebook>=6.4.0
  - ipython
  - pip:
    - openai-whisper
    - pyannote.audio>=2.0.0
    - pyannote.metrics
    - resemblyzer>=0.1.0
    - pydub>=0.25.1
    - webrtcvad>=2.0.10
    - transformers>=4.18.0
    - torch>=1.10.0
    - torchaudio>=0.10.0
    - soundfile>=0.10.3
